### PR TITLE
[Maro/#13] feat :: 3주차 구현 완료

### PR DESCRIPTION
**Pull request by leesumin0526**
**Viewpager**
- HomeFragment [banner] 
- AlbumFragment (TabLayout)
- AlbumFragment, DetailFragment, VideoFragment
- LockerFragment (TabLayout)

**Indicator**
    - HomeFragment (Panel Viewpager & CircleIndicator
    - Auto Slide

### CODE REVIEW

**Review by hyowon0204 — APPROVED** [review]
짱 좋아용

**Review by BAEK0111 — APPROVED** [review]
코드 멋진데요

**Comment by leesumin0526** [comment]
🥇

**Review by Ssamssamukja — APPROVED** [review]
좋습니더~~ 👍

**Pull request merged**
